import Events from "../../components/modules/Events";
import Head from "next/head";

import styles from "../../styles/modules/Events.module.scss";

const AllEvents = () => {
    return (
        <>
            <Head itemScope itemType="http://schema.org/WPHeader">
                <title itemProp="headline">Проведенные мероприятия</title>
                <meta
                    itemProp="description"
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    itemProp="keywords"
                    name="keywords"
                    content="ключевые_слова_для_страницы"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Events limit={false} />
        </>
    );
};
export default AllEvents;
