import Head from "next/head";
import Favorites from "../components/modules/Favorites";
const favorites = () => {
    return (
        <>
            <Head itemScope itemType="http://schema.org/WPHeader">
                <title itemProp="headline">Избранные</title>
                <meta
                    itemProp="description"
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    itemProp="keywords"
                    name="keywords"
                    content="ключевые_слова_для_страницы"
                />
            </Head>
            <Favorites />
        </>
    );
};

export default favorites;
