import Head from "next/head";
import Hero from "../components/home/Hero";
import Rent from "../components/home/Rent";
import Gallery from "../components/home/Gallery";
import Gifts from "../components/modules/Gifts";
import Events from "../components/modules/Events";
import FAQ from "../components/modules/FAQ";
import Feedback from "../components/modules/Feedback";

// DATA
import StepsData from "../public/data/home/steps.json";
import RentData from "../public/data/home/rent.json";
import GalleryData from "../public/data/home/gallery.json";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="FoodTruck" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero obj={StepsData} />
            <Rent arr={RentData} />
            <Gallery obj={GalleryData} />
            <Gifts />
            <Events />
            <FAQ />
            <Feedback />
        </div>
    );
}
