import Head from "next/head";
import Hero from "../components/stations/Hero";
import Catalog from "../components/modules/Catalog";
import Upsale from "../components/modules/Upsale";

// DATA
import CatalogData from "../public/data/stations/catalog.json";
import UpsaleData from "../public/data/stations/upsale.json";

export default function FoodTrucks() {
    return (
        <>
            <Head itemScope itemType="http://schema.org/WPHeader">
                <title itemProp="headline">Кулинарные станции</title>
                <meta
                    itemProp="description"
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    itemProp="keywords"
                    name="keywords"
                    content="ключевые_слова_для_страницы"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <Catalog bucket={true} obj={CatalogData} />
            <Upsale obj={UpsaleData} />
        </>
    );
}
